### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by slowdivePTG** [AtomyChan/PmPyeasy#1]
When I was trying to plot the light curves after calibration by running

```python
sn.lc_plot('calmag') #or 'relmag' or anything else
```

an index error occurred when the pipeline was trying to attach the legend

```python
plt.legend(flts_plot)
```

in line 8298 of `photcore.py`.

**Comment by AtomyChan** [comment]
The updated version of lc_plot() function corrected the issue.
